version: '3'
services:
  meli:
    container_name: meli-server
    ports:
      - 8000:8000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/go/src/meli
    working_dir: /go/src/meli
    depends_on:
      - db
      - redis
    env_file:
      - ./config/.env.docker-compose
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - 16379:6379
    container_name: meli-redis
    networks:
      - backend

networks:
  backend:
